### ISSUE TITLE
Java: fieldMax is not correct on bit field 

### ISSUE THREAD

**Issue by Matt-Osminer-CardinalPeak** [MilesEngineering/MsgTools#22]
See TestCase1 -> FieldAFieldInfo.max

Quick look the code looks like it should work fine.  However the returned value is not only wrong, it's a long and requires a 'L' specifier.

**Comment by mgazic** [comment]
I looked at generated code for TestCase1 FieldAFieldInfo.max and didn't see a problem.  I also built the code into AndroidServer and got no compile errors.  I'm going to assume this was fixed.
