### ISSUE TITLE
Add Travis Status images to README

### ISSUE THREAD

**Issue by mosminerCP** [MilesEngineering/MsgTools#80]
Handy to see build status  right on the home page after checking stuff in.

https://docs.travis-ci.com/user/status-images/

**Comment by mgazic** [comment]
Cool!

**Comment by mosminerCP** [comment]
Note: On a skim read of the docs, It appears you have to be the repo owner to do this.  Which is why I didn't just do it. :)

**Comment by mgazic** [comment]
I updated the README.md
