### ISSUE TITLE
Support the base 'msg' option consistently

### ISSUE THREAD

**Issue by mosminerCP** [MilesEngineering/MsgTools#85]
The msg option is specified as part of the base App (app.py), however the functionality is implemented at the tool level (inspector, multilog).  We should either move the command line option/feature up to the tool level and not make it a base option, or implement the functionality at the base level for all utilities.

I'd be inclined to do the latter, however @mgazic I think you hold the vision of MsgTools and should weigh in on which way you want to go.  Once decided this is a pretty easy change to make.

**Comment by mgazic** [comment]
> I'd be inclined to do the latter
Agreed, implement at the base level for all utilities sounds good to me.  Looks like there's currently two places in app.py where RxMsg is emitted, and one where ProcessMessage is called directly.
